#
# clients/email
#

all: $(EXES)


include $(ARCHIE_ROOT)/Makefile.post


email-client: \
               $(LIBARCHIE_MODULE)/$(SYSTYPE)/libarchie.a \
               $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(MOD_LIBS) $(SYS_LIBS)

clean:
	rm -f *.o $(EXES) email-client core
