#
# Anonftp/lib  module.
#

#MOD_CFLAGS = -ansi -pedantic -pipe
#MOD_CFLAGS = -pipe
MOD_DEBUG  = -g3
MOD_WARN   = -Wall -Wtraditional -Wshadow -Wpointer-arith -Wcast-align \
             -Wstrict-prototypes -Wnested-externs

MOD_INCS = -I$(CLIENT_MODULE)/telnet

include $(ARCHIE_ROOT)/Makefile.pre


#INCS = \
#	email.h		\
#	lang_email.h

SRCS = \
	split_file.c


OBJS = \
	split_file.o


EXES = \
	split_file


