#ifndef LOCAL_ATTRS_H
#define LOCAL_ATTRS_H

#define CONTENTS         "CONTENTS"
#define EXECUTABLE       "BUNYIP-EXECUTABLE"
#define HEADLINE         "BUNYIP-HEADLINE"
#define HEADLINE_FORMAT  "BUNYIP-HEADLINE-FORMAT"
#define IMAGE_MAP        "BUNYIP-IMAGE-MAP"
#define POSE_AS          "BUNYIP-POSE-AS"
#define REPLACE_WITH_URL "BUNYIP-REPLACE-WITH-URL"
#define SEARCH_HELP_URL  "BUNYIP-SEARCH-HELP-URL"
#define RESTRICTED_ACCESS "BUNYIP-RESTRICTED-ACCESS"

#endif
