#
# anonftp/retrieve module.
#

all: $(EXES)


include $(ARCHIE_ROOT)/Makefile.post


retrieve_anonftp: \
                   $(LIBARCHIE_MODULE)/$(SYSTYPE)/libarchie.a \
                   $(HOSTDB_MODULE)/$(SYSTYPE)/libhostdb.a    \
                   ${OBJS}
	${CC} ${CFLAGS} -o $@ ${OBJS} ${MOD_LIBS} ${SYS_LIBS}

clean:
	rm -f *.o $(EXES) core
