#ifndef _WAIS_ATTRIB_H_
#define _WAIS_ATTRIB_H_

typedef enum{

   WAIS_DOC_LEN = 0x01,

#define	SET_WAIS_DOC_LEN(x)	((x) |= WAIS_DOC_LEN)
#define	UNSET_WAIS_DOC_LEN(x)	((x) &= ~WAIS_DOC_LEN)
#define	GET_WAIS_DOC_LEN(x)	((x) & WAIS_DOC_LEN)

#define	NAME_WAIS_DOC_LEN  "WAIS_DOC_LEN"

   WAIS_DOC_LINES = 0x02,

#define	SET_WAIS_DOC_LINES(x)	((x) |= WAIS_DOC_LINES)
#define	UNSET_WAIS_DOC_LINES(x)	((x) &= ~WAIS_DOC_LINES)
#define	GET_WAIS_DOC_LINES(x)	((x) & WAIS_DOC_LINES)

#define	NAME_WAIS_DOC_LINES  "WAIS_DOC_LINES"

   WAIS_DOC_SCORE = 0x04,

#define	SET_WAIS_DOC_SCORE(x)	((x) |= WAIS_DOC_SCORE)
#define	UNSET_WAIS_DOC_SCORE(x)	((x) &= ~WAIS_DOC_SCORE)
#define	GET_WAIS_DOC_SCORE(x)	((x) & WAIS_DOC_SCORE)

#define	NAME_WAIS_DOC_SCORE  "WAIS_DOC_SCORE"


   WAIS_DOC_VERSION = 0x08,

#define	SET_WAIS_DOC_VERSION(x)	((x) |= WAIS_DOC_VERSION)
#define	UNSET_WAIS_DOC_VERSION(x)	((x) &= ~WAIS_DOC_VERSION)
#define	GET_WAIS_DOC_VERSION(x)	((x) & WAIS_DOC_VERSION)

#define	NAME_WAIS_DOC_VERSION  "WAIS_DOC_VERSION"

   WAIS_DOC_BESTMATCH = 0x10,

#define	SET_WAIS_DOC_BESTMATCH(x)	((x) |= WAIS_DOC_BESTMATCH)
#define	UNSET_WAIS_DOC_BESTMATCH(x)	((x) &= ~WAIS_DOC_BESTMATCH)
#define	GET_WAIS_DOC_BESTMATCH(x)	((x) & WAIS_DOC_BESTMATCH)

#define	NAME_WAIS_DOC_BESTMATCH  "WAIS_DOC_BESTMATCH"

   WAIS_DOC_DATE = 0x20,

#define	SET_WAIS_DOC_DATE(x)	((x) |= WAIS_DOC_DATE)
#define	UNSET_WAIS_DOC_DATE(x)	((x) &= ~WAIS_DOC_DATE)
#define	GET_WAIS_DOC_DATE(x)	((x) & WAIS_DOC_DATE)

#define	NAME_WAIS_DOC_DATE  "WAIS_DOC_DATE"

   WAIS_DOC_SOURCE = 0x40,

#define	SET_WAIS_DOC_SOURCE(x)	((x) |= WAIS_DOC_SOURCE)
#define	UNSET_WAIS_DOC_SOURCE(x)	((x) &= ~WAIS_DOC_SOURCE)
#define	GET_WAIS_DOC_SOURCE(x)	((x) & WAIS_DOC_SOURCE)

#define	NAME_WAIS_DOC_SOURCE  "WAIS_DOC_SOURCE"

   WAIS_DOC_TYPES = 0x80,

#define	SET_WAIS_DOC_TYPES(x)	((x) |= WAIS_DOC_TYPES)
#define	UNSET_WAIS_DOC_TYPES(x)	((x) &= ~WAIS_DOC_TYPES)
#define	GET_WAIS_DOC_TYPES(x)	((x) & WAIS_DOC_TYPES)

#define	NAME_WAIS_DOC_TYPES  "WAIS_DOC_TYPES"

   WAIS_DOC_CONTENT = 0x100,

#define	SET_WAIS_DOC_CONTENT(x)	((x) |= WAIS_DOC_CONTENT)
#define	UNSET_WAIS_DOC_CONTENT(x)	((x) &= ~WAIS_DOC_CONTENT)
#define	GET_WAIS_DOC_CONTENT(x)	((x) & WAIS_DOC_CONTENT)

#define	NAME_WAIS_DOC_CONTENT  "WAIS_DOC_CONTENT"



} wais_attrib_t;

#endif
